name: Generate IndiaNavi Tiles for SD card 
on:
  push:
    branches: 
      - '*'
  pull_request:

jobs:
  install_pip_and_generate:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v3
      with:
        path: tiles/png
        key: ${{ runner.os }}-tiles-${{ hashFiles('sq_loader.py') }}
        restore-keys: |
          ${{ runner.os }}-tiles-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Setup XServer
      run: |
        sudo apt update 
        sudo apt install xvfb -y
        sudo apt install imagemagick -y

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt         
    
    - name: Run splash converter
      run: python gen_splash.py 

    - name: Run tile converter
      run: python sq_loader.py

    - name: Take screenshot
      run: |
          chmod +x ./indianavi
          xvfb-run ./indianavi --screenshot
          convert frame.pnm frame.png

    - name: Upload screenshot
      uses: edunad/actions-image@v1.0.1
      with:
          path: 'frame.png'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          title: '🚶‍♂️'
